import type { Metadata } from 'next'
import { themeConfig } from '@/lib/theme.config'
import { ThemeProvider, ThemeScript } from '@vapor-ui/core'
import '@vapor-ui/core/dist/styles.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // 'suppressHydrationWarning'은 필수입니다.
    // 서버와 클라이언트의 초기 테마 속성 불일치로 인한 경고를 방지합니다.
    <html lang='ko' suppressHydrationWarning>
      <head>
        {/* FOUC 방지를 위한 스크립트입니다.
            <head> 태그의 최상단에 위치하는 것을 권장합니다. */}
        <ThemeScript config={themeConfig} />
      </head>
      <body>
        {/* 동적 테마 관리를 위한 프로바이더 */}
        <ThemeProvider config={themeConfig}>
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
