import type { Metadata } from 'next'
import { ThemeClientProvider } from '@/components/ThemeClientProvider'
import '@vapor-ui/core/styles.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // 'suppressHydrationWarning'은 필수입니다.
    // 서버와 클라이언트의 초기 테마 속성 불일치로 인한 경고를 방지합니다.
    <html lang='ko' suppressHydrationWarning>
      <head>
        {/* FOUC 방지를 위한 스크립트는 ThemeClientProvider 내부에서 처리됩니다 */}
      </head>
      <body>
        <ThemeClientProvider>{children}</ThemeClientProvider>
      </body>
    </html>
  )
}
